# Generated by Django 5.2.11 on 2026-02-11 11:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.CharField(max_length=50)),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['opis_id'], name='routing_tru_opis_id_21c1a7_idx'), models.Index(fields=['retail_price'], name='routing_tru_retail__18db7c_idx'), models.Index(fields=['location'], name='routing_tru_locatio_6af6ea_idx')],
            },
        ),
    ]
